### ISSUE TITLE
save favorites to localStorage

### ISSUE THREAD

**Issue by lenmorld** [lenmorld/meme-app#1]
right now the favorites are just in memory
implement saving to local storage

**Comment by pollyj** [comment]
@lenmorld Hi! Can I help with this?

**Comment by lenmorld** [comment]
Sure I'll assign it to you

**Comment by pollyj** [comment]
Hi @lenmorld, I opened a PR https://github.com/lenmorld/meme-app/pull/4 with changes that solve this issue. Let me know if you want anything else adding!

**Comment by adhammo** [comment]
Can you at least mark my PR #3 as hacktoberfest-accepted. I posted it 3 hours earlier to hers.
