### ISSUE TITLE
UI/UX improvement for Unfavorite

### ISSUE THREAD

**Issue by lenmorld** [lenmorld/meme-app#6]
Currently, to Unfavorite (remove a Favorite item), user has to double-click.
This is not a very obvious UI, so please implement something better.
Probably something close to the heart emoji for the favorites with a suitable emoji/icon.

Bonus if you can implement an iconset too, both for the favorite and unfavorite.

**Comment by mohanyadav** [comment]
Hi @lenmorld 
Can you assign me this?

Thanks
